#!/usr/bin/env node
/**
 * CONTEXT MANAGEMENT SYSTEM
 * Implements the "CLEAR/COMPRESS ritual" from the vibe coding series
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

class ContextManager {
  constructor(projectRoot = process.cwd()) {
    this.root = projectRoot;
    this.summaryDir = path.join(this.root, '.claude-sessions');
    this.maxContextSize = 100000; // 100k tokens approx
  }

  // Auto-summarize current session work
  async summarizeSession(sessionName = null) {
    const name = sessionName || `session-${Date.now()}`;

    const summary = {
      timestamp: new Date().toISOString(),
      sessionName: name,
      changes: this.getRecentChanges(),
      issues: this.detectIssues(),
      nextSteps: this.suggestNextSteps(),
      contextSize: this.estimateContextSize()
    };

    // Save summary
    if (!fs.existsSync(this.summaryDir)) {
      fs.mkdirSync(this.summaryDir, { recursive: true });
    }

    const summaryFile = path.join(this.summaryDir, `${name}.md`);
    fs.writeFileSync(summaryFile, this.formatSummary(summary));

    return { summary, file: summaryFile };
  }

  getRecentChanges() {
    try {
      const diff = execSync('git diff HEAD~1..HEAD --stat', {
        cwd: this.root,
        encoding: 'utf8'
      }).trim();

      const log = execSync('git log -1 --pretty=format:"%h - %s"', {
        cwd: this.root,
        encoding: 'utf8'
      }).trim();

      return { diff, log };
    } catch {
      return { diff: 'No git changes', log: 'Not a git repo' };
    }
  }

  detectIssues() {
    const issues = [];

    // Check for TODOs
    try {
      const todos = execSync('grep -r "TODO\\|FIXME\\|HACK" --include="*.js" --include="*.ts" .', {
        cwd: this.root,
        encoding: 'utf8'
      }).trim().split('\n').slice(0, 10);

      if (todos.length > 0 && todos[0]) {
        issues.push({ type: 'todos', count: todos.length, items: todos });
      }
    } catch {}

    // Check for failing tests
    try {
      execSync('npm test 2>&1', { cwd: this.root, stdio: 'pipe' });
    } catch {
      issues.push({ type: 'failing_tests', message: 'Tests are failing' });
    }

    return issues;
  }

  suggestNextSteps() {
    const steps = [];

    // Based on git status
    try {
      const status = execSync('git status --porcelain', {
        cwd: this.root,
        encoding: 'utf8'
      }).trim();

      if (status) {
        steps.push('Commit pending changes');
      }
    } catch {}

    // Based on package.json scripts
    try {
      const pkg = JSON.parse(fs.readFileSync(path.join(this.root, 'package.json'), 'utf8'));
      if (pkg.scripts) {
        if (pkg.scripts.test) steps.push('Run test suite');
        if (pkg.scripts.build) steps.push('Verify build');
        if (pkg.scripts.lint) steps.push('Check linting');
      }
    } catch {}

    return steps;
  }

  estimateContextSize() {
    // Rough estimate based on file sizes
    const jsFiles = this.findFiles('**/*.{js,ts,jsx,tsx}');
    let totalSize = 0;

    for (const file of jsFiles.slice(0, 100)) {
      try {
        const stats = fs.statSync(file);
        totalSize += stats.size;
      } catch {}
    }

    const estimatedTokens = Math.floor(totalSize / 4); // ~4 chars per token
    return { bytes: totalSize, estimatedTokens };
  }

  formatSummary(summary) {
    return `# Session Summary: ${summary.sessionName}

**Date:** ${summary.timestamp}

## Recent Changes
\`\`\`
${summary.changes.log}
\`\`\`

### Diff Stats
\`\`\`
${summary.changes.diff}
\`\`\`

## Issues Detected
${summary.issues.length === 0 ? 'None' : summary.issues.map(i =>
  `- **${i.type}**: ${i.message || i.count + ' items'}`
).join('\n')}

## Next Steps
${summary.nextSteps.map(s => `- [ ] ${s}`).join('\n')}

## Context Size
- Bytes: ${summary.contextSize.bytes.toLocaleString()}
- Estimated Tokens: ${summary.contextSize.estimatedTokens.toLocaleString()}

---
*Auto-generated by Context Manager*
`;
  }

  findFiles(pattern) {
    try {
      const result = execSync(`find . -name "${pattern}" -type f 2>/dev/null || echo ""`, {
        cwd: this.root,
        encoding: 'utf8'
      });
      return result.trim().split('\n').filter(Boolean);
    } catch {
      return [];
    }
  }

  // Load previous session summary
  loadLastSummary() {
    if (!fs.existsSync(this.summaryDir)) return null;

    const files = fs.readdirSync(this.summaryDir)
      .filter(f => f.endsWith('.md'))
      .sort()
      .reverse();

    if (files.length === 0) return null;

    const lastFile = path.join(this.summaryDir, files[0]);
    return fs.readFileSync(lastFile, 'utf8');
  }

  // Check if context reset needed
  shouldResetContext() {
    const ctx = this.estimateContextSize();
    return ctx.estimatedTokens > this.maxContextSize;
  }
}

// CLI
if (require.main === module) {
  const manager = new ContextManager();

  const command = process.argv[2];

  if (command === 'summarize') {
    manager.summarizeSession(process.argv[3]).then(result => {
      console.log('✓ Session summarized:', result.file);
      console.log('\nSummary:');
      console.log(result.summary.nextSteps.join('\n'));
    });
  } else if (command === 'load') {
    const summary = manager.loadLastSummary();
    console.log(summary || 'No previous summaries found');
  } else if (command === 'check') {
    const should = manager.shouldResetContext();
    console.log(should ? 'Context reset recommended' : 'Context size OK');
    process.exit(should ? 1 : 0);
  } else {
    console.log('Usage: context-manager.js [summarize|load|check]');
  }
}

module.exports = ContextManager;
