/**
 * Test-Driven Development Workflow Manager
 * Enforces TDD patterns: Write Failing Tests → Implement → Pass Tests
 */

import { EventEmitter } from 'events';
import { exec } from 'child_process';
import { promisify } from 'util';
import { writeFile, readFile } from 'fs/promises';
import path from 'path';

const execAsync = promisify(exec);

export class TDDWorkflow extends EventEmitter {
  constructor(options = {}) {
    super();
    this.projectRoot = options.projectRoot || process.cwd();
    this.testFramework = options.testFramework || 'jest';
    this.testDirectory = options.testDirectory || 'tests';
    this.currentCycle = null;
  }

  async startTDDCycle(featureName, requirements = {}) {
    this.currentCycle = {
      feature: featureName,
      id: `tdd-${Date.now()}`,
      startTime: Date.now(),
      state: 'write-test',
      iterations: [],
      requirements,
    };

    this.emit('tdd:started', this.currentCycle);
    return this.currentCycle.id;
  }

  async writeFailingTest(testSpec) {
    if (!this.currentCycle || this.currentCycle.state !== 'write-test') {
      throw new Error(`Cannot write test from ${this.currentCycle?.state || 'idle'} state`);
    }

    const testFile = path.join(
      this.projectRoot,
      this.testDirectory,
      testSpec.fileName || `${this.currentCycle.feature}.test.js`
    );

    const testCode = this.generateTestTemplate(testSpec);

    await writeFile(testFile, testCode, 'utf-8');

    this.emit('test:written', { file: testFile, code: testCode });

    const testResult = await this.runTests(testFile);

    if (testResult.passed) {
      throw new Error('Test must fail initially - test is passing when it should fail');
    }

    this.currentCycle.testFile = testFile;
    this.currentCycle.state = 'implement';
    this.currentCycle.initialFailure = testResult;

    this.emit('test:failed-correctly', { testFile, result: testResult });

    return {
      testFile,
      failure: testResult,
      nextState: 'implement',
    };
  }

  generateTestTemplate(testSpec) {
    const templates = {
      jest: this.generateJestTemplate(testSpec),
      pytest: this.generatePytestTemplate(testSpec),
    };

    return templates[this.testFramework] || templates.jest;
  }

  generateJestTemplate(testSpec) {
    return `/**
 * Test Suite: ${testSpec.description || 'Feature Test'}
 * Generated by TDD Workflow
 */

describe('${testSpec.feature || 'Feature'}', () => {
  test('${testSpec.testName || 'should work correctly'}', () => {
    // Arrange
    ${testSpec.arrange || '// Set up test data'}

    // Act
    ${testSpec.act || '// Execute the code under test'}

    // Assert
    ${testSpec.assert || 'expect(true).toBe(false); // This should fail initially'}
  });

  ${testSpec.additionalTests || ''}
});
`;
  }

  generatePytestTemplate(testSpec) {
    return `"""
Test Suite: ${testSpec.description || 'Feature Test'}
Generated by TDD Workflow
"""

def test_${testSpec.testName?.replace(/\s+/g, '_') || 'feature'}():
    # Arrange
    ${testSpec.arrange || '# Set up test data'}

    # Act
    ${testSpec.act || '# Execute the code under test'}

    # Assert
    ${testSpec.assert || 'assert False, "This should fail initially"'}
`;
  }

  async runTests(testFile = null) {
    const commands = {
      jest: testFile ? `npm test -- "${testFile}"` : 'npm test',
      pytest: testFile ? `pytest "${testFile}"` : 'pytest',
      mocha: testFile ? `npm test -- "${testFile}"` : 'npm test',
    };

    const command = commands[this.testFramework] || commands.jest;

    try {
      const { stdout, stderr } = await execAsync(command, { cwd: this.projectRoot });

      const result = this.parseTestOutput(stdout, stderr);

      this.emit('tests:run', result);

      return result;
    } catch (error) {
      const result = this.parseTestOutput(error.stdout || '', error.stderr || '');
      result.error = error.message;

      this.emit('tests:run', result);

      return result;
    }
  }

  parseTestOutput(stdout, stderr) {
    const output = stdout + stderr;

    const passed = /(\d+) passed/i.exec(output);
    const failed = /(\d+) failed/i.exec(output);
    const total = /(\d+) total/i.exec(output);

    return {
      passed: !output.toLowerCase().includes('failed') && !output.toLowerCase().includes('error'),
      passedCount: passed ? parseInt(passed[1]) : 0,
      failedCount: failed ? parseInt(failed[1]) : 0,
      totalCount: total ? parseInt(total[1]) : 0,
      output: output.trim(),
      timestamp: Date.now(),
    };
  }

  async implementFeature(implementation) {
    if (!this.currentCycle || this.currentCycle.state !== 'implement') {
      throw new Error(`Cannot implement from ${this.currentCycle?.state || 'idle'} state`);
    }

    this.currentCycle.implementation = {
      ...implementation,
      timestamp: Date.now(),
    };

    this.currentCycle.state = 'verify';

    this.emit('implementation:complete', this.currentCycle.implementation);

    return this.currentCycle.implementation;
  }

  async verifyImplementation() {
    if (!this.currentCycle || this.currentCycle.state !== 'verify') {
      throw new Error(`Cannot verify from ${this.currentCycle?.state || 'idle'} state`);
    }

    this.emit('verification:start', { cycleId: this.currentCycle.id });

    const testResult = await this.runTests(this.currentCycle.testFile);

    const iteration = {
      timestamp: Date.now(),
      testResult,
      passed: testResult.passed,
    };

    this.currentCycle.iterations.push(iteration);

    if (testResult.passed) {
      this.currentCycle.state = 'refactor';
      this.currentCycle.completedAt = Date.now();
      this.currentCycle.duration = this.currentCycle.completedAt - this.currentCycle.startTime;

      this.emit('tdd:cycle-complete', this.currentCycle);

      return {
        success: true,
        nextState: 'refactor',
        testResult,
      };
    } else {
      this.currentCycle.state = 'implement';

      this.emit('verification:failed', { testResult });

      return {
        success: false,
        nextState: 'implement',
        testResult,
        message: 'Tests still failing - continue implementation',
      };
    }
  }

  async refactor(changes) {
    if (!this.currentCycle || this.currentCycle.state !== 'refactor') {
      throw new Error(`Cannot refactor from ${this.currentCycle?.state || 'idle'} state`);
    }

    this.currentCycle.refactoring = {
      changes,
      timestamp: Date.now(),
    };

    this.emit('refactor:start', changes);

    const testResult = await this.runTests(this.currentCycle.testFile);

    if (!testResult.passed) {
      this.emit('refactor:broke-tests', { testResult });

      return {
        success: false,
        message: 'Refactoring broke tests - revert changes',
        testResult,
      };
    }

    this.currentCycle.state = 'complete';

    this.emit('refactor:complete', { changes, testResult });

    return {
      success: true,
      nextState: 'complete',
      testResult,
    };
  }

  async completeCycle() {
    if (!this.currentCycle) {
      throw new Error('No active TDD cycle');
    }

    const completedCycle = {
      ...this.currentCycle,
      completedAt: Date.now(),
      duration: Date.now() - this.currentCycle.startTime,
      success: this.currentCycle.state === 'complete',
    };

    this.emit('tdd:finished', completedCycle);

    this.currentCycle = null;

    return completedCycle;
  }

  async generateTestCoverage() {
    try {
      const { stdout } = await execAsync('npm test -- --coverage', { cwd: this.projectRoot });

      const coverage = this.parseCoverageOutput(stdout);

      this.emit('coverage:generated', coverage);

      return coverage;
    } catch (error) {
      this.emit('coverage:error', { error });
      return null;
    }
  }

  parseCoverageOutput(output) {
    const lines = /Lines\s*:\s*([\d.]+)%/i.exec(output);
    const branches = /Branches\s*:\s*([\d.]+)%/i.exec(output);
    const functions = /Functions\s*:\s*([\d.]+)%/i.exec(output);
    const statements = /Statements\s*:\s*([\d.]+)%/i.exec(output);

    return {
      lines: lines ? parseFloat(lines[1]) : 0,
      branches: branches ? parseFloat(branches[1]) : 0,
      functions: functions ? parseFloat(functions[1]) : 0,
      statements: statements ? parseFloat(statements[1]) : 0,
    };
  }

  getCycleStatus() {
    if (!this.currentCycle) {
      return { active: false };
    }

    return {
      active: true,
      feature: this.currentCycle.feature,
      state: this.currentCycle.state,
      iterations: this.currentCycle.iterations.length,
      duration: Date.now() - this.currentCycle.startTime,
    };
  }

  async runFullTDDWorkflow(featureSpec) {
    await this.startTDDCycle(featureSpec.name, featureSpec);

    await this.writeFailingTest({
      feature: featureSpec.name,
      testName: featureSpec.testName,
      description: featureSpec.description,
      assert: featureSpec.assert,
    });

    return {
      cycleId: this.currentCycle.id,
      nextAction: 'implement',
      message: 'Test written and failing as expected. Ready for implementation.',
    };
  }
}

export default TDDWorkflow;
