/**
 * A2A System Configuration Constants
 * Centralized configuration values to avoid magic numbers
 */

// Network Configuration
export const NETWORK = {
  BRIDGE_WS_PORT: 65028,
  BRIDGE_HTTP_PORT: 65029,
  RECONNECT_BASE_DELAY_MS: 1000,
  RECONNECT_MAX_DELAY_MS: 30000,
  RECONNECT_JITTER_MS: 1000,
  WEBSOCKET_TIMEOUT_MS: 30000,
  HTTP_REQUEST_TIMEOUT_MS: 5000,
  PING_INTERVAL_MS: 30000,
  PONG_TIMEOUT_MS: 10000,
};

// Performance & Resource Management
export const PERFORMANCE = {
  MAX_LOG_ENTRIES: 150,
  MAX_STORED_LOGS: 1000,
  LOG_BATCH_DELAY_MS: 100,
  HEARTBEAT_INTERVAL_MS: 120000, // 2 minutes
  METRICS_UPDATE_INTERVAL_MS: 15000, // 15 seconds
  AGENT_HEALTH_UPDATE_INTERVAL_MS: 10000, // 10 seconds
  STATS_BROADCAST_INTERVAL_MS: 10000, // 10 seconds
  CLEANUP_INTERVAL_MS: 120000, // 2 minutes
  CLIENT_LIST_POLL_INTERVAL_MS: 20000, // 20 seconds
  HEALTH_CHECK_DEBOUNCE_MS: 3000,
  BRIDGE_STARTUP_DELAY_MS: 3000,
  AGENT_STARTUP_STAGGER_MS: 800,
  BRIDGE_RECONNECT_DELAY_MS: 5000,
};

// Agent Configuration
export const AGENTS = {
  MAX_RESTART_ATTEMPTS: 3,
  RESTART_BACKOFF_BASE_MS: 2000,
  RESTART_RESET_WINDOW_MS: 300000, // 5 minutes
  GRACEFUL_SHUTDOWN_TIMEOUT_MS: 5000,
  HEARTBEAT_HEALTHY_THRESHOLD_MS: 5000,
  HEARTBEAT_WARNING_THRESHOLD_MS: 30000,
};

// DevTools Configuration
export const DEVTOOLS = {
  CDP_PORT: 9222,
  CDP_HOST: 'localhost',
  ERROR_THRESHOLD: 3,
  SLOW_REQUEST_MS: 1000,
  SAMPLING_INTERVAL_MS: 5000,
  MEMORY_LEAK_MB: 50,
  MAX_CONSOLE_ERRORS: 100,
  MAX_NETWORK_REQUESTS: 1000,
  PERFORMANCE_SAMPLES: 100,
};

// Message Queue & History
export const MESSAGING = {
  HISTORY_LIMIT: 50,
  MAX_QUEUE_PER_CLIENT: 50,
  MAX_TOTAL_QUEUED: 1000,
  CLIENT_TTL_MS: 600000, // 10 minutes
  MAX_PAYLOAD_SIZE_BYTES: 2 * 1024 * 1024, // 2MB
  MESSAGE_PREVIEW_LENGTH: 80,
};

// LLM Configuration
export const LLM = {
  OLLAMA: {
    DEFAULT_MODEL: 'llama3',
    DEFAULT_TEMPERATURE: 0.7,
    DEFAULT_TOP_P: 0.9,
    DEFAULT_TOP_K: 40,
    DEFAULT_NUM_PREDICT: 512,
    DEFAULT_NUM_CTX: 4096,
    DEFAULT_NUM_THREAD: 4,
    REQUEST_TIMEOUT_MS: 30000,
    MAX_RETRIES: 2,
    RETRY_DELAY_MS: 1000,
  },
  FOUNDRY_LOCAL: {
    DEFAULT_MODEL: 'phi-3.5-mini',
    DEFAULT_TEMPERATURE: 0.7,
    DEFAULT_MAX_TOKENS: 1024,
    MODEL_TTL_MS: 600000, // 10 minutes
    AUTO_START: true,
    HARDWARE_PREFERENCE: 'auto', // auto|cpu|gpu|npu
    REQUEST_TIMEOUT_MS: 30000,
    MAX_CONCURRENT_REQUESTS: 2, // NPU memory constraint
  },
  CACHE: {
    MAX_SIZE: 100,
    TTL_MS: 300000, // 5 minutes
  },
};

// UI & Display
export const UI = {
  TOAST_DURATION_MS: 5000,
  PERFORMANCE_GRAPH_POINTS: 60,
  MAX_MESSAGE_PREVIEW_LENGTH: 50,
  COMPRESSION_LEVEL: 1,
  COMPRESSION_THRESHOLD_BYTES: 4096,
  CONCURRENCY_LIMIT: 5,
  DOM_BATCH_SIZE: 20,
  VIRTUAL_SCROLL_ITEM_HEIGHT: 50,
  VIRTUAL_SCROLL_BUFFER: 5,
  RENDER_THROTTLE_MS: 100,
  CACHE_RESPONSE_TTL_MS: 5000,
};

// Security
export const SECURITY = {
  RATE_LIMIT_WINDOW_MS: 60000,
  RATE_LIMIT_MAX_REQUESTS: 120,
  ALLOWED_ORIGINS: ['*'],
  TOKEN_AUTH_ENABLED: false,
};

// System Metadata
export const SYSTEM = {
  VERSION: '1.2.0',
  APP_NAME: 'A2A Control Center',
  BRIDGE_VERSION: '1.1.0',
};

export default {
  NETWORK,
  PERFORMANCE,
  AGENTS,
  MESSAGING,
  LLM,
  UI,
  SECURITY,
  SYSTEM,
};
