/**
 * Docker image builder
 * Converts build plans into Dockerfiles and builds OCI-compliant images
 *
 * @module llmpacks/docker-builder
 */

import fs from 'fs/promises';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import { logger } from '../utils/logger.js';

const execAsync = promisify(exec);

/**
 * Generate Dockerfile from build plan
 * @param {Object} buildPlan - Build plan with phases
 * @returns {string} Dockerfile content
 */
function generateDockerfile(buildPlan) {
  const lines = [];

  // Determine base image
  let baseImage = 'node:18-alpine';
  if (buildPlan.provider === 'python') {
    baseImage = `python:${buildPlan.version || '3.11'}-slim`;
  } else if (buildPlan.provider === 'go') {
    baseImage = `golang:${buildPlan.version || '1.21'}-alpine`;
  } else if (buildPlan.provider === 'nodejs' || buildPlan.provider === 'electron') {
    const nodeVersion = buildPlan.version?.replace(/[^0-9.]/g, '') || '18';
    baseImage = `node:${nodeVersion}-alpine`;
  }

  lines.push(`# Generated by LLMPacks v${buildPlan.llmpacksVersion || '1.0.0'}`);
  lines.push(`# Provider: ${buildPlan.provider}`);
  lines.push(`# Cache Key: ${buildPlan.cacheKey}`);
  lines.push('');

  // Multi-stage build for production
  lines.push('# Stage 1: Build');
  lines.push(`FROM ${baseImage} AS builder`);
  lines.push('');

  lines.push('# Set working directory');
  lines.push('WORKDIR /app');
  lines.push('');

  // Install system dependencies if specified
  if (buildPlan.systemDependencies && buildPlan.systemDependencies.length > 0) {
    lines.push('# Install system dependencies');
    if (baseImage.includes('alpine')) {
      lines.push(`RUN apk add --no-cache ${buildPlan.systemDependencies.join(' ')}`);
    } else {
      lines.push(`RUN apt-get update && apt-get install -y ${buildPlan.systemDependencies.join(' ')} && rm -rf /var/lib/apt/lists/*`);
    }
    lines.push('');
  }

  // Process install phase
  const installPhase = buildPlan.phases.find(p => p.name === 'install');
  if (installPhase) {
    lines.push('# Install dependencies');

    // Copy dependency files first (for layer caching)
    if (buildPlan.provider === 'nodejs' || buildPlan.provider === 'electron') {
      lines.push('COPY package*.json ./');
      lines.push('COPY yarn.lock* pnpm-lock.yaml* ./');
    } else if (buildPlan.provider === 'python') {
      lines.push('COPY requirements.txt* Pipfile* pyproject.toml* ./');
    } else if (buildPlan.provider === 'go') {
      lines.push('COPY go.mod go.sum* ./');
    }
    lines.push('');

    // Run install commands
    for (const command of installPhase.commands) {
      lines.push(`RUN ${command}`);
    }
    lines.push('');
  }

  // Copy source code
  lines.push('# Copy source code');
  lines.push('COPY . .');
  lines.push('');

  // Process build phase
  const buildPhase = buildPlan.phases.find(p => p.name === 'build');
  if (buildPhase) {
    lines.push('# Build application');

    // Set environment variables for build
    if (buildPhase.environment) {
      for (const [key, value] of Object.entries(buildPhase.environment)) {
        lines.push(`ENV ${key}=${value}`);
      }
      lines.push('');
    }

    // Run build commands
    for (const command of buildPhase.commands) {
      lines.push(`RUN ${command}`);
    }
    lines.push('');
  }

  // Stage 2: Production runtime
  lines.push('# Stage 2: Production');
  lines.push(`FROM ${baseImage}`);
  lines.push('');

  lines.push('WORKDIR /app');
  lines.push('');

  // Install production system dependencies only
  if (buildPlan.systemDependencies && buildPlan.systemDependencies.length > 0) {
    lines.push('# Install runtime dependencies');
    if (baseImage.includes('alpine')) {
      lines.push(`RUN apk add --no-cache ${buildPlan.systemDependencies.join(' ')}`);
    } else {
      lines.push(`RUN apt-get update && apt-get install -y ${buildPlan.systemDependencies.join(' ')} && rm -rf /var/lib/apt/lists/*`);
    }
    lines.push('');
  }

  // Copy from builder stage
  lines.push('# Copy from builder');
  if (buildPlan.provider === 'nodejs' || buildPlan.provider === 'electron') {
    lines.push('COPY --from=builder /app/node_modules ./node_modules');
    lines.push('COPY --from=builder /app/package*.json ./');
  }

  // Copy built artifacts
  if (buildPhase && buildPhase.outputDirectory) {
    lines.push(`COPY --from=builder /app/${buildPhase.outputDirectory} ./${buildPhase.outputDirectory}`);
  } else {
    lines.push('COPY --from=builder /app ./');
  }
  lines.push('');

  // Process start phase
  const startPhase = buildPlan.phases.find(p => p.name === 'start');
  if (startPhase) {
    // Set runtime environment variables
    if (startPhase.environment) {
      lines.push('# Runtime environment');
      for (const [key, value] of Object.entries(startPhase.environment)) {
        lines.push(`ENV ${key}=${value}`);
      }
      lines.push('');
    }

    // Expose port
    if (startPhase.port) {
      lines.push(`EXPOSE ${startPhase.port}`);
      lines.push('');
    }

    // Set start command
    lines.push('# Start command');
    if (Array.isArray(startPhase.command)) {
      lines.push(`CMD ${JSON.stringify(startPhase.command)}`);
    } else {
      const cmdParts = startPhase.command.split(' ');
      lines.push(`CMD ${JSON.stringify(cmdParts)}`);
    }
  }

  return lines.join('\n');
}

/**
 * Build Docker image from build plan
 * @param {Object} options - Build options
 * @param {string} options.projectPath - Path to project directory
 * @param {Object} options.buildPlan - Build plan
 * @param {string} options.imageName - Docker image name
 * @param {string} options.tag - Image tag
 * @param {boolean} options.push - Whether to push image to registry
 * @returns {Promise<Object>} Build result with image info
 */
export async function buildDockerImage(options) {
  const { projectPath, buildPlan, imageName, tag, push } = options;

  logger.info('Building Docker image', { imageName, tag });

  try {
    // Generate Dockerfile
    const dockerfile = generateDockerfile(buildPlan);
    const dockerfilePath = path.join(projectPath, 'Dockerfile.llmpacks');

    // Write Dockerfile
    await fs.writeFile(dockerfilePath, dockerfile, 'utf-8');
    logger.debug('Dockerfile generated', { path: dockerfilePath });

    // Build image
    const fullImageName = `${imageName}:${tag}`;
    const buildCommand = `docker build -f ${dockerfilePath} -t ${fullImageName} ${projectPath}`;

    logger.info('Running docker build...', { command: buildCommand });

    const { stdout, stderr } = await execAsync(buildCommand, {
      maxBuffer: 10 * 1024 * 1024 // 10MB buffer
    });

    if (stderr && !stderr.includes('naming to')) {
      logger.warn('Docker build warnings', { stderr });
    }

    logger.debug('Docker build output', { stdout: stdout.substring(0, 500) });

    // Get image info
    const inspectCommand = `docker inspect ${fullImageName}`;
    const { stdout: inspectOutput } = await execAsync(inspectCommand);
    const imageInfo = JSON.parse(inspectOutput)[0];

    const result = {
      imageName: fullImageName,
      imageId: imageInfo.Id,
      size: imageInfo.Size,
      layers: imageInfo.RootFS?.Layers?.length || 0,
      created: imageInfo.Created,
      dockerfilePath
    };

    // Push to registry if requested
    if (push) {
      logger.info('Pushing image to registry...', { imageName: fullImageName });

      const pushCommand = `docker push ${fullImageName}`;
      const { stdout: pushOutput } = await execAsync(pushCommand);

      logger.debug('Push output', { stdout: pushOutput });
      result.pushed = true;
      result.registry = pushOutput.match(/([^ ]+): digest:/)?.[1] || 'unknown';
    }

    logger.success('Docker image built successfully', {
      imageName: result.imageName,
      size: (result.size / 1024 / 1024).toFixed(2) + ' MB',
      layers: result.layers
    });

    return result;
  } catch (error) {
    logger.error('Docker build failed', {
      error: error.message,
      stderr: error.stderr
    });
    throw new Error(`Docker build failed: ${error.message}`);
  }
}

/**
 * Generate Dockerfile content without building
 * @param {Object} buildPlan - Build plan
 * @returns {string} Dockerfile content
 */
export function generateDockerfileContent(buildPlan) {
  return generateDockerfile(buildPlan);
}

/**
 * Validate Docker is installed and running
 * @returns {Promise<boolean>} True if Docker is available
 */
export async function validateDockerAvailable() {
  try {
    await execAsync('docker --version');
    await execAsync('docker ps');
    return true;
  } catch (error) {
    logger.error('Docker validation failed', { error: error.message });
    return false;
  }
}

export default buildDockerImage;
