#!/usr/bin/env node
/**
 * security-agent-1 - Auto-generated by Meta-Agent Factory
 * Description: Scans for security vulnerabilities
 * Generated: 2025-10-20T10:39:06.392Z
 */

import WebSocket from 'ws';
import dotenv from 'dotenv';
import { logger } from '../utils/logger.js';

dotenv.config();

const BRIDGE_WS = process.env.BRIDGE_WS || 'ws://localhost:65028';
const AGENT_ID = 'security-agent-1';

class SecurityAgent1Agent {
  constructor() {
    this.agentId = AGENT_ID;
    this.ws = null;
    this.capabilities = ["sql_injection_check","xss_detection","dependency_audit"];
    this.intents = ["security.scan","security.audit","security.report"];
  }

  async connect() {
    logger.info(`🤖 ${this.agentId} connecting...`);
    this.ws = new WebSocket(BRIDGE_WS);

    await new Promise((resolve, reject) => {
      this.ws.on('open', resolve);
      this.ws.on('error', reject);
    });

    this.ws.send(JSON.stringify({
      type: 'register',
      clientId: this.agentId,
      role: 'Scans for security vulnerabilities',
      labels: ['auto-generated', 'specialized', 'security-agent-1'],
      tools: this.capabilities,
      intents: this.intents,
      maxConcurrentTasks: 3
    }));

    await new Promise(r => this.ws.once('message', r));
    logger.info(`✅ ${this.agentId} ready\n`);

    this.setupHandlers();
  }

  setupHandlers() {
    this.ws.on('message', async (data) => {
      const msg = JSON.parse(data.toString());
      if (Array.isArray(msg) && msg[0] === 'env') {
        await this.handleEnvelope(msg[1]);
      }
    });

    this.ws.on('close', () => {
      logger.info('🔌 Disconnected - reconnecting...');
      setTimeout(() => this.connect(), 5000);
    });

    this.ws.on('error', (err) => {
      logger.error('❌ WebSocket error:', err.message);
    });

    setInterval(() => {
      if (this.ws.readyState === WebSocket.OPEN) {
        this.ws.ping();
      }
    }, 60000);
  }

  async handleEnvelope(envelope) {
    const { from, intent, payload, id } = envelope;

    logger.info(`\n📨 Processing request: ${intent}`);

    try {
      // Auto-generated agent logic
      const result = await this.processTask(intent, payload);

      this.ws.send(JSON.stringify({
        type: 'envelope',
        envelope: {
          from: this.agentId,
          to: from,
          intent: `${intent}.result`,
          replyTo: id,
          payload: result
        }
      }));

    } catch (error) {
      logger.error('❌ Error processing task:', error.message);
      this.ws.send(JSON.stringify({
        type: 'envelope',
        envelope: {
          from: this.agentId,
          to: from,
          intent: 'agent.error',
          replyTo: id,
          payload: { error: error.message }
        }
      }));
    }
  }

  async processTask(intent, payload) {
    logger.info(`🔧 Processing: ${intent}`);

    // Handle security-specific intents
    if (intent === 'security.scan' || intent === 'security.audit') {
      return await this.runSecurityAudit(payload);
    }

    if (intent === 'security.report') {
      return await this.getSecurityReport();
    }

    // Default task processing
    const result = {
      agent: this.agentId,
      intent,
      status: 'completed',
      timestamp: new Date().toISOString(),
      payload,
      capabilities: this.capabilities,
      message: `Task processed by security agent`
    };

    return result;
  }

  async runSecurityAudit(options = {}) {
    const { execSync } = await import('child_process');
    const fs = await import('fs');

    try {
      logger.info('Running optimized security audit...');

      const output = execSync('npm run security:audit', {
        encoding: 'utf8',
        timeout: 120000,
        maxBuffer: 10 * 1024 * 1024
      });

      // Read the generated report
      const reportPath = 'reports/security-audit-report.json';
      const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));

      return {
        agent: this.agentId,
        status: 'completed',
        timestamp: new Date().toISOString(),
        audit: report,
        message: 'Security audit completed successfully'
      };
    } catch (error) {
      logger.error('Security audit failed:', error.message);
      return {
        agent: this.agentId,
        status: 'failed',
        timestamp: new Date().toISOString(),
        error: error.message,
        message: 'Security audit encountered errors'
      };
    }
  }

  async getSecurityReport() {
    const fs = await import('fs');

    try {
      const reportPath = 'reports/security-audit-report.json';

      if (!fs.existsSync(reportPath)) {
        return {
          agent: this.agentId,
          status: 'not_found',
          message: 'No security report available. Run security.scan first.'
        };
      }

      const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));

      return {
        agent: this.agentId,
        status: 'completed',
        timestamp: new Date().toISOString(),
        report,
        message: 'Security report retrieved successfully'
      };
    } catch (error) {
      logger.error('Failed to get security report:', error.message);
      return {
        agent: this.agentId,
        status: 'failed',
        error: error.message
      };
    }
  }
}

// Start agent
const agent = new SecurityAgent1Agent();
agent.connect().catch(err => {
  logger.error('❌ Failed to connect:', err ? (err.message || JSON.stringify(err)) : 'Unknown error');
  console.error('Full error:', err);
  process.exit(1);
});

// Catch unhandled rejections
process.on('unhandledRejection', (reason, promise) => {
  logger.error('Unhandled rejection:', reason);
  console.error('Unhandled rejection at:', promise, 'reason:', reason);
});

process.on('SIGINT', () => {
  logger.info('\n👋 Shutting down security-agent-1...');
  process.exit(0);
});
